Repository PanicControlSolution/Project, pull requests merged in 2023-04, with the labels that each got.

#6 Completed User Story 10
  .github/workflows/build.yml
Labels: enhancement

#5 Completed User Story 11
  .github/workflows/build.yml
  Lab5.Persistence/Data/AppDbContext.cs
  Lab5.Persistence/UnitOfWork/EfUnitOfWork.cs
  Lab5.Persistence/UnitOfWork/FakeUnitOfWork.cs
  Lab5.UI/App.xaml.cs
  Lab5.UI/Lab5.UI.csproj
  Lab5.UI/MauiProgram.cs
  Lab5.UI/Platforms/Android/MainActivity.cs
  Lab5.UI/Platforms/Android/MainApplication.cs
  Lab5.UI/Platforms/MacCatalyst/AppDelegate.cs
  Lab5.UI/Platforms/MacCatalyst/Program.cs
  Lab5.UI/Platforms/Tizen/Main.cs
  Lab5.UI/Platforms/Tizen/tizen-manifest.xml
  Lab5.UI/Platforms/Windows/App.xaml.cs
  Lab5.UI/Platforms/iOS/AppDelegate.cs
  Lab5.UI/Platforms/iOS/Info.plist
  Lab5.UI/Platforms/iOS/Program.cs
Labels: enhancement

#7 UserStory12 done
  Lab5.UI/AppShell.xaml
  Lab5.UI/Lab5.UI.csproj
  Lab5.UI/MauiProgram.cs
  Lab5.UI/Pages/MainPage.xaml
  Lab5.UI/Pages/MainPage.xaml.cs
  Lab5.UI/Pages/Sets.xaml
  Lab5.UI/Pages/Sets.xaml.cs
  Lab5.UI/ViewModels/SetViewModel.cs
Labels: enhancement

#13 Fixed codestyle
  Lab5.Application/Services/SetService.cs
  Lab5.Application/Services/SushiService.cs
  Lab5.UI/AppShell.xaml
  Lab5.UI/Pages/Sets.xaml
  Lab5.UI/Platforms/Android/AndroidManifest.xml
  Lab5.UI/Platforms/Android/Resources/values/colors.xml
  Lab5.UI/Platforms/Windows/App.xaml
Labels: documentation, enhancement

#16 Fixed ViewModel issue
  .github/workflows/build.yml
  Lab5.UI/Pages/MainPage.xaml.cs
  Lab5.UI/Pages/Sets.xaml.cs
  Lab5.UI/ViewModels/SetViewModel.cs
Labels: bug, enhancement

#17 Userstory/16
  Lab5.Application/Services/SetService.cs
  Lab5.Domain/Entities/Entity.cs
  Lab5.Domain/Entities/Set.cs
  Lab5.Domain/Entities/Sushi.cs
  Lab5.Domain/Lab5.Domain.csproj
  Lab5.Persistence/Data/AppDbContext.cs
  Lab5.Persistence/Lab5.Persistence.csproj
  Lab5.Persistence/Repository/FakeRepositories.cs
Labels: enhancement

#19 Done User Story 18
  Lab5.Domain/Entities/Entity.cs
  Lab5.Domain/Entities/Set.cs
  Lab5.Domain/Entities/Sushi.cs
Labels: enhancement

#20 Removed useless fields
  Lab5.Persistence/Repository/FakeRepositories.cs
Labels: enhancement

#22 Fixed repository work
  Lab5.Application/Services/SetService.cs
  Lab5.Persistence/Repository/FakeRepositories.cs
  Lab5.Persistence/UnitOfWork/FakeUnitOfWork.cs
Labels: bug, enhancement

#21 Moved MainPage to Pages UI
  Lab5.UI/AppShell.xaml
  Lab5.UI/Pages/MainPage.xaml
  Lab5.UI/Pages/MainPage.xaml.cs
Labels: enhancement

#24 userstory13
  Lab5.Application/Services/SetService.cs
  Lab5.Domain/Entities/Set.cs
  Lab5.Persistence/Data/AppDbContext.cs
  Lab5.Persistence/Repository/EfRepository.cs
  Lab5.Persistence/Repository/FakeRepositories.cs
  Lab5.Persistence/UnitOfWork/EfUnitOfWork.cs
  Lab5.UI/Lab5.UI.csproj
  Lab5.UI/MauiProgram.cs
  Lab5.UI/Pages/MainPage.xaml
  Lab5.UI/Pages/Sets.xaml
  Lab5.UI/ViewModels/SetViewModel.cs
  Lab5.UI/appsettings.json
Labels: enhancement

#23 Userstory/12 (Converter implementation) is done
  Lab5.Persistence/Repository/FakeRepositories.cs
  Lab5.UI/Lab5.UI.csproj
  Lab5.UI/Pages/Sets.xaml
  Lab5.UI/ValueConverters/CountToColorValueConverter.cs
Labels: enhancement

#27 userstory/16
  Lab5.UI/AppShell.xaml
  Lab5.UI/Lab5.UI.csproj
  Lab5.UI/Pages/MainPage.xaml
  Lab5.UI/Resources/Images/dotnet_bot.svg
  Lab5.UI/Resources/Images/home.png
  Lab5.UI/Resources/Images/sushi.png
Labels: enhancement

#28 Minor fixes
  Lab5.Domain/Entities/Entity.cs
  Lab5.Domain/Entities/Set.cs
  Lab5.Domain/Entities/Sushi.cs
  Lab5.Persistence/Data/AppDbContext.cs
  Lab5.Persistence/Repository/EfRepository.cs
  Lab5.Persistence/Repository/FakeRepositories.cs
  Lab5.UI/AppShell.xaml
  Lab5.UI/MauiProgram.cs
  Lab5.UI/Pages/Sets.xaml
  Lab5.UI/ViewModels/SetViewModel.cs
  Lab5.UI/appsettings.json
Labels: bug, enhancement
